### ISSUE TITLE
Shared state can make client unusable

### ISSUE THREAD

**Issue by dodumosu** [andela-sjames/paystack-python#41]
Ran into an issue where I was getting 401 errors, even though my secret key was in the environment.

This works with `os.environ['PAYSTACK_SECRET_KEY']` set:

```
Transaction.initialize(amount=amount, email=email, reference=reference)
client = Paystack()  # secret_key not explicitly set
client.transaction.initialize(amount=amount, email=email, reference=reference)
````

This doesn't, even with `os.environ['PAYSTACK_SECRET_KEY']` set:
```
client = Paystack() # secret_key not explicity set
client.transaction.initialize(amount=amount, email=email, reference=reference)

# using the Transaction class itself now fails
Transaction.initialize(amount=amount, email=email, reference=reference)
```

**Comment by andela-sjames** [comment]
Interesting, that's odd @dodumosu did you instantiate using the specified format from the readme?
Please try this format and let me know if this is helpful. 

```python
from paystackapi.paystack import Paystack

paystack_secret_key = "5om3secretK3y"  
paystack = Paystack(secret_key=paystack_secret_key)  
```

**Comment by andela-sjames** [comment]
@dodumosu you might also want to `explicitly` set your secret_key; the library uses that approach except you prefer the other method of using the library. 

I suppose the readme is not clear on that; I'll try to improve on it.
