### ISSUE TITLE
Transactions verification

### ISSUE THREAD

**Issue by Geeker1** [andela-sjames/paystack-python#43]
Good Day, have been using the paystack js pattern to make transactions now but I decided to switch to the paystack version for django, when I do Transaction.initialize it works and payment is successful, but I see other Transaction implementations there. Is it ok to do only Transaction initialize or I have to implement others thanks....

**Comment by jcobhams** [comment]
I don't understand your issue. More context please

**Comment by Geeker1** [comment]
I know that if make a Transaction.initialize() it gives me a json response where I can redirect to the payment page, but how do I make callbacks in case the transaction fails, like redirecting to a url of my choice

**Comment by andela-sjames** [comment]
https://developers.paystack.co/v2.0/reference

From the docs 👆 pass in a `callback_url` argument with a value
e.g

```python
Transaction.initialize(reference='reference', amount='amount', email='email'
                       callback_url="https://callback_url.com")
```
You can reference the docs to see other arguments to pass in as `**kwargs**`, I hope this helps.

**Comment by Geeker1** [comment]
It does help, thanks a lot....
