### ISSUE TITLE
adding a callback_url

### ISSUE THREAD

**Issue by nodebe** [andela-sjames/paystack-python#48]
How can I add a callback_url so that after payment, it redirects to the url function for verification. I am  using flask

**Comment by andela-sjames** [comment]
From the docs https://developers.paystack.co/v2.0/reference pass in a callback_url argument with a value

e.g
```
Transaction.initialize(reference='reference', amount='amount', email='email'
                       callback_url="https://callback_url.com")
```
You can reference the docs to see other arguments to pass in as **kwargs**, I hope this helps.

**Comment by andela-sjames** [comment]
Closing this
