### ISSUE TITLE
Trying to initialize my transaction in USD, Since the default is NGN?

### ISSUE THREAD

**Issue by nodebe** [andela-sjames/paystack-python#52]
response = Transaction.initialize(reference=uuid, amount=amount, email='myemail@gmail.com', currency='USD')
But it is returning unauthorized

**Comment by andela-sjames** [comment]
Did you set your secret key?

**Comment by nodebe** [comment]
yes I did

**Comment by nodebe** [comment]
the currency parameter is not passing. It passes sucessfully when I remove the currency. How can I make the user see that he/she is paying in dollars

**Comment by andela-sjames** [comment]
@nodebe please reference Paystack as this is not an issue with the Library
https://paystack.com/blog/product/new-accept-payments-in-usd

This link talks about enabling it from your Paystack account dashboard. I know this because I had a chat with the Paystack team sometime ago.
