### ISSUE TITLE
I can't disable otp successfully

### ISSUE THREAD

**Issue by nodebe** [andela-sjames/paystack-python#73]
I am trying to disable otp but it keeps telling me that otp has been sent to number that ends with 3996. That isn't the number I used to register on my paystack

![Capture](https://user-images.githubusercontent.com/23224489/82138985-a9976900-981c-11ea-9712-604d54edfda8.JPG)

**Comment by andela-sjames** [comment]
Please refer to the README
> Don't forget to get your API key from Paystack and assign to the variable PAYSTACK_SECRET_KEY

You should not use my API key but yours. You are getting that error because you are not using your personal  API key, may I suggest that you do so. The number in that message belongs to me. Please get yours and use.

**Comment by andela-sjames** [comment]
Please refer to the README
> Don't forget to get your API key from Paystack and assign to the variable PAYSTACK_SECRET_KEY

You should not use my API key but yours. You are getting that error because you are not using your personal  API key, may I suggest that you do so. The number in that message belongs to me. Please get yours and use.
