### ISSUE TITLE
Add ability to pass arguments to `Misc.list_banks()`

### ISSUE THREAD

**Issue by samitnuk** [andela-sjames/paystack-python#82]
Currently, when I use `Misc.list_banks()` I gen 67 banks but all of them are for Nigeria.

There should be the possibility to pass query params (see: [List Banks](https://paystack.com/docs/api/#miscellaneous-bank)) to get banks filtered by country, currency etc.

Probably `Misc.list_banks()` should accept arguments in the same way as `SubAccount.list()`:
https://github.com/andela-sjames/paystack-python/blob/84ce37b17dcdbd039267bb2d8d3f6999831a3525/paystackapi/subaccount.py#L26-L38

**Comment by Aptcoder** [comment]
Hello @andela-sjames. I think this would be a good addition and will like to work on it. Do I get the go ahead?

**Comment by andela-sjames** [comment]
Go ahead, it's a community project

**Comment by andela-sjames** [comment]
Merged and added to new release @Aptcoder @samitnuk 
https://github.com/andela-sjames/paystack-python/releases/tag/v2.1.0
