### ISSUE TITLE
No options for query parameters for transaction listing

### ISSUE THREAD

**Issue by Strapchay** [andela-sjames/paystack-python#92]
There is no options for query parameter when using the transaction class. For example using paystacks plain url, its possible to do something like:
f"https://api.paystack.co/transaction?use_cursor=true&perPage=10&customer={x}"
But the list endpoint for the transaction doesn't receive any params.

**Comment by Strapchay** [comment]
Have made a pull requests that addresses this issue since its more or less a low handing fruit: https://github.com/andela-sjames/paystack-python/pull/93

**Comment by sharhan-alhassan** [comment]
Hey @Strapchay Facing the same issue, was coming to make a PR on the query params for that resource but seems you've done that already. Any status on whether it went in?

**Comment by Strapchay** [comment]
I had no issues using the data, there might be a possibility if the pull request not being accepted or not being accepted within your needed time frame, so I would advice you should either fork my repo or create a repo for yourself and use the forked repo in your project

**Comment by sharhan-alhassan** [comment]
> I had no issues using the data, there might be a possibility if the pull request not being accepted or not being accepted within your needed time frame, so I would advice you should either fork my repo or create a repo for yourself and use the forked repo in your project

Hey buddy, that sounds good to me. Thank you

**Comment by andela-sjames** [comment]
Thanks for making the changes, let me update this

**Comment by sharhan-alhassan** [comment]
> Thanks for making the changes, let me update this

Thank you @andela-sjames 
I'll be opening another issue and a possible PR on that for Subscription resource

**Comment by andela-sjames** [comment]
> > Thanks for making the changes, let me update this
> 
> Thank you @andela-sjames I'll be opening another issue and a possible PR on that for Subscription resource

Please don't forget to update the doc folder and test if possible on the next PR, I will release an update in a moment

**Comment by sharhan-alhassan** [comment]
> > > Thanks for making the changes, let me update this
> > 
> > 
> > Thank you @andela-sjames I'll be opening another issue and a possible PR on that for Subscription resource
> 
> Please don't forget to update the doc folder and test if possible on the next PR, I will release an update in a moment

Awesome! Will definitely do that
